### ISSUE TITLE
neurips eval notes

### ISSUE THREAD

**Issue by binaryaaron** [teja1729/LLM_Challenge#1]
hi! 

I don't have access to push a new branch here; if you allow me to i'll submit a PR for us vs a patch. you can try applying it via ```
git apply patch.PATCH
```.

This is a diff that allows us to properly evaluate (e.g., train a new model with your code and data on our infra).

[patch.PATCH](https://github.com/teja1729/LLM_Challenge/files/13398664/patch.PATCH)

**Comment by teja1729** [comment]
patch was applied and pushed to the main branch 

Added you as collaborator as well

**Comment by binaryaaron** [comment]
thank you! @msaroufim , i think this is good to go now.
